### ISSUE TITLE
加入 lm-menu 組織?

### ISSUE THREAD

**Issue by JixunMoe** [lm-menu/lunar-magic-chinese-translating#1]
https://github.com/lm-menu

**Comment by JixunMoe** [comment]
參見：
https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by tcdw** [comment]
人家说我没有鹳狸猿权限 QAQ

**Comment by JixunMoe** [comment]
現在呢..

**Comment by tcdw** [comment]
完毕
